receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
  memory_limiter:
    limit_mib: 1800
    spike_limit_mib: 500
    check_interval: 5s

extensions:
  health_check: {}
  zpages: {}

exporters:
  clickhouse:
    endpoint: tcp://clickhouse:9000
    database: otel
    traces_table_name: otel_traces
    timeout: 10s
    sending_queue:
      enabled: true
      queue_size: 100
      num_consumers: 10
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

service:
  extensions: [ health_check, zpages ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ clickhouse ]
